/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2023-05-03 05:06:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.entities.Category;
import java.util.ArrayList;
import com.techblog.helper.ConnectionProvider;
import java.sql.Connection;
import com.techblog.dao.PostDao;
import com.entities.Message;
import com.model.User;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("com.model.User");
    _jspx_imports_classes.add("com.entities.Category");
    _jspx_imports_classes.add("com.techblog.dao.PostDao");
    _jspx_imports_classes.add("com.techblog.helper.ConnectionProvider");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.entities.Message");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error-page.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

User user = (User) session.getAttribute("currentUser");
if (user == null) {
	response.sendRedirect("login-page.jsp");
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<!-- css -->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"mystyle.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".banner-background {\r\n");
      out.write("	clip-path: polygon(30% 0%, 100% 0, 100% 30%, 100% 93%, 66% 100%, 34% 92%, 0 100%, 0\r\n");
      out.write("		0);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<title>Profile Page</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- navbar -->\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-dark primary-background\">\r\n");
      out.write("		<a class=\"navbar-brand\" href=\"#\"><span class=\"fa fa-asterisk\"></span>\r\n");
      out.write("			Tech Blog</a>\r\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("			data-target=\"#navbarSupportedContent\"\r\n");
      out.write("			aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("			aria-label=\"Toggle navigation\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("			<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("				<li class=\"nav-item active\"><a class=\"nav-link\"\r\n");
      out.write("					href=\"index.jsp\"><span class=\"fa fa-home\"></span> Home</a></li>\r\n");
      out.write("				<li class=\"nav-item dropdown\"><a\r\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("					role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("					aria-expanded=\"false\"><span class=\"fa fa-navicon\"></span>\r\n");
      out.write("						Categories </a>\r\n");
      out.write("					<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("						<a class=\"dropdown-item\" href=\"#\">Programming Language</a> <a\r\n");
      out.write("							class=\"dropdown-item\" href=\"#\">Project Implementation</a>\r\n");
      out.write("						<div class=\"dropdown-divider\"></div>\r\n");
      out.write("						<a class=\"dropdown-item\" href=\"#\">Data Structure</a>\r\n");
      out.write("					</div></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"><span\r\n");
      out.write("						class=\"fa fa-phone-square\"></span> Contacts</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
      out.write("					data-toggle=\"modal\" data-target=\"#post-modal\"><span\r\n");
      out.write("						class=\"fa fa-send\"></span> Post</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<ul class=\"navbar-nav mr-right\">\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"#!\"\r\n");
      out.write("					data-toggle=\"modal\" data-target=\"#profile-modal\"><span\r\n");
      out.write("						class=\"fa fa-user-circle\"></span> ");
      out.print(user.getName());
      out.write("</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"LogoutServlet\"><span\r\n");
      out.write("						class=\"fa fa-toggle-on\"></span> Logout</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- end of navbar -->\r\n");
      out.write("\r\n");
      out.write("	");

	Message m = (Message) session.getAttribute("msg");
	if (m != null) {
	
      out.write("\r\n");
      out.write("	<div class=\"alert ");
      out.print(m.getCssClass());
      out.write("\" role=\"alert\">\r\n");
      out.write("		");
      out.print(m.getContent());
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	");

	session.removeAttribute("msg");
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- main body of the page -->\r\n");
      out.write("\r\n");
      out.write("	<main>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row mt-4\">\r\n");
      out.write("				<!-- firs col -->\r\n");
      out.write("				<div class=\"col-md-4\">\r\n");
      out.write("					<!-- categories -->\r\n");
      out.write("					<div class=\"list-group\">\r\n");
      out.write("						<a href=\"#\" onclick=\"getPosts(0,this)\"\r\n");
      out.write("							class=\"c-link list-group-item list-group-item-action active\">\r\n");
      out.write("							All Posts </a>\r\n");
      out.write("\r\n");
      out.write("						");

						PostDao d = new PostDao(ConnectionProvider.getConnection());
						ArrayList<Category> list1 = d.getAllCategories();
						for (Category cc : list1) {
						
      out.write("\r\n");
      out.write("						<a href=\"#\" onclick=\"getPosts(");
      out.print(cc.getCid());
      out.write(",this)\"\r\n");
      out.write("							class=\"c-link list-group-item list-group-item-action\">");
      out.print(cc.getName());
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- second col -->\r\n");
      out.write("				<div class=\"col-md-8\" id=\"post-container\">\r\n");
      out.write("					<!-- posts -->\r\n");
      out.write("					<div class=\"container text-center\" id=\"loader\">\r\n");
      out.write("						<i class=\"fa fa-refresh fa-4x fa-spin\"></i>\r\n");
      out.write("						<h3 class=\"mt-2\">Loading...</h3>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("	<!-- end main body of the page -->\r\n");
      out.write("\r\n");
      out.write("	<!-- profile modal -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"profile-modal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header primary-background text-white\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"exampleModalLabel\">TechBlog</h5>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<div class=\"container text-center\">\r\n");
      out.write("						<h5 class=\"modal-title\" id=\"exampleModalLabel\">");
      out.print(user.getName());
      out.write("</h5>\r\n");
      out.write("						<!-- Details -->\r\n");
      out.write("						<div id=\"profile-details\">\r\n");
      out.write("							<table class=\"table\">\r\n");
      out.write("								<tbody>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"row\">ID :</th>\r\n");
      out.write("										<td>");
      out.print(user.getId());
      out.write("</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"row\">Email :</th>\r\n");
      out.write("										<td>");
      out.print(user.getEmail());
      out.write("</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"row\">Gender :</th>\r\n");
      out.write("										<td>");
      out.print(user.getGender().toUpperCase());
      out.write("</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</tbody>\r\n");
      out.write("							</table>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- profile edit -->\r\n");
      out.write("						<div id=\"profile-edit\" style=\"display: none\">\r\n");
      out.write("							<h3 class=\"mt-2\">Please Edit Carefully</h3>\r\n");
      out.write("							<form action=\"EditServlet\" method=\"post\">\r\n");
      out.write("								<table class=\"table\">\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td>ID :</td>\r\n");
      out.write("										<td>");
      out.print(user.getId());
      out.write("</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td>Name :</td>\r\n");
      out.write("										<td><input type=\"text\" class=\"form-control\" name=\"name\"\r\n");
      out.write("											value=\"");
      out.print(user.getName());
      out.write("\"></td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td>Email :</td>\r\n");
      out.write("										<td><input type=\"email\" class=\"form-control\" name=\"email\"\r\n");
      out.write("											value=\"");
      out.print(user.getEmail());
      out.write("\"></td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td>Password :</td>\r\n");
      out.write("										<td><input type=\"password\" class=\"form-control\"\r\n");
      out.write("											name=\"password\" value=\"");
      out.print(user.getPassword());
      out.write("\"></td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td>Gender :</td>\r\n");
      out.write("										<td>");
      out.print(user.getGender().toUpperCase());
      out.write("</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</table>\r\n");
      out.write("								<div class=\"container\">\r\n");
      out.write("									<button type=\"submit\" class=\"btn btn-primary\">Save</button>\r\n");
      out.write("								</div>\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-dismiss=\"modal\">Close</button>\r\n");
      out.write("					<button id=\"edit-profile-btn\" type=\"button\" class=\"btn btn-primary\">Edit</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- end of profile modal -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Post modal -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"post-modal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"exampleModalLabel\">Provide the\r\n");
      out.write("						post details..</h5>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<form id=\"post-form\" action=\"PostServlet\" method=\"post\"\r\n");
      out.write("						enctype=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<select class=\"form-control\" name=\"cid\">\r\n");
      out.write("								<option selected=\"selected\" disabled=\"disabled\">---Select\r\n");
      out.write("									Category---</option>\r\n");
      out.write("\r\n");
      out.write("								");

								PostDao postd = new PostDao(ConnectionProvider.getConnection());
								ArrayList<Category> list = postd.getAllCategories();

								for (Category c : list) {
								
      out.write("\r\n");
      out.write("								<option value=\"");
      out.print(c.getCid());
      out.write('"');
      out.write('>');
      out.print(c.getName());
      out.write("</option>\r\n");
      out.write("								");

								}
								
      out.write("\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<input name=\"pTitle\" type=\"text\" placeholder=\"Enter post Title\"\r\n");
      out.write("								class=\"form-control\" />\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<textarea name=\"pContent\" class=\"form-control\"\r\n");
      out.write("								placeholder=\"Enter your content\"></textarea>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<textarea name=\"pCode\" class=\"form-control\"\r\n");
      out.write("								placeholder=\"Enter your program (if any)\"></textarea>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label>Select your pic</label> <br> <input type=\"file\"\r\n");
      out.write("								name=\"pPic\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"container text-center\">\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-outline-primary\">Post</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-dismiss=\"modal\">Back</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- end of post modal -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Javascripts -->\r\n");
      out.write("\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.3.min.js\"\r\n");
      out.write("		integrity=\"sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\"\r\n");
      out.write("		integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js\"\r\n");
      out.write("		integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js\"\r\n");
      out.write("		integrity=\"sha512-AA1Bzp5Q0K1KanKKmvN/4d3IRKVlv9PYgwFPvm32nPO6QS8yH1HO7LbgB1pgiOxPtfeg5zEn2ba64MUcqJx6CA==\"\r\n");
      out.write("		crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-ajaxy/1.6.1/scripts/jquery.ajaxy.min.js\"\r\n");
      out.write("		integrity=\"sha512-bztGAvCE/3+a1Oh0gUro7BHukf6v7zpzrAb3ReWAVrt+bVNNphcl2tDTKCBr5zk7iEDmQ2Bv401fX3jeVXGIcA==\"\r\n");
      out.write("		crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("	<script src=\"my.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("			let editStatus = false;\r\n");
      out.write("\r\n");
      out.write("			$('#edit-profile-btn').click(function() {\r\n");
      out.write("				if (editStatus == false) {\r\n");
      out.write("					$('#profile-details').hide()\r\n");
      out.write("\r\n");
      out.write("					$('#profile-edit').show()\r\n");
      out.write("					editStatus = true;\r\n");
      out.write("					$(this).text(\"Back\")\r\n");
      out.write("				} else {\r\n");
      out.write("					$('#profile-details').show()\r\n");
      out.write("\r\n");
      out.write("					$('#profile-edit').hide()\r\n");
      out.write("					editStatus = false;\r\n");
      out.write("					$(this).text(\"Edit\")\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- adding post using ajax -->\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		$(document).ready(function(e) {\r\n");
      out.write("			$(\"#post-form\").on(\"submit\", function(event) {\r\n");
      out.write("				event.preventDefault();\r\n");
      out.write("				//console.log(\"you have clicked on save..\")\r\n");
      out.write("				let form = new FormData(this);\r\n");
      out.write("				/* now requesting to server */\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url: \"PostServlet\",\r\n");
      out.write("					type: 'post',\r\n");
      out.write("					data: form,\r\n");
      out.write("					success: function(data){\r\n");
      out.write("						if(data.trim()=='done'){\r\n");
      out.write("							swal(\"Good job!\", \"Post uploaded successfully!\", \"success\");\r\n");
      out.write("						}else{\r\n");
      out.write("							swal(\"Error!!\", \"Something went wrong try again!!\", \"error\");\r\n");
      out.write("						}\r\n");
      out.write("					},\r\n");
      out.write("					error: function(data){\r\n");
      out.write("						swal(\"Error!!\", \"Something went wrong try again!!\", \"error\");\r\n");
      out.write("					},\r\n");
      out.write("					processData: false,\r\n");
      out.write("					contentType: false\r\n");
      out.write("				})\r\n");
      out.write("			})\r\n");
      out.write("		})\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<!-- loading post using ajax -->\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function getPosts(catId,temp) {\r\n");
      out.write("			$(\"#loader\").show();\r\n");
      out.write("			$(\"#post-container\").hide();\r\n");
      out.write("			$(\".c-link\").removeClass('active')\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"load-posts.jsp\",\r\n");
      out.write("				data : {cid : catId},\r\n");
      out.write("				success : function(data) {\r\n");
      out.write("					console.log(data);\r\n");
      out.write("					$(\"#loader\").hide();\r\n");
      out.write("					$(\"#post-container\").show();\r\n");
      out.write("					$(\"#post-container\").html(data)\r\n");
      out.write("					$(temp).addClass('active')\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		$(document).ready(function(e) {\r\n");
      out.write("			\r\n");
      out.write("			let allPostRef = $('.c-link')[0]\r\n");
      out.write("			getPosts(0, allPostRef)\r\n");
      out.write("\r\n");
      out.write("		})\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
